# Generated by Django 5.2.7 on 2025-12-22 16:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_brands', models.ManyToManyField(blank=True, related_name='favorited_by', to='products.brand')),
                ('favorite_categories', models.ManyToManyField(blank=True, related_name='favorited_by', to='products.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='CollectorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('details', 'View Details'), ('moreDetails', 'View More Details'), ('buy', 'Purchase'), ('addToCart', 'Add to Cart')], max_length=20)),
                ('session_id', models.CharField(blank=True, help_text='Session ID cho anonymous users', max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, help_text='mobile, tablet, desktop', max_length=50, null=True)),
                ('platform', models.CharField(blank=True, help_text='web, android, ios', max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Additional data: variant_id, quantity, price, etc.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector_logs', to='products.product')),
                ('user', models.ForeignKey(blank=True, help_text='Null for anonymous users', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collector_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collector_logs',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='collector_l_user_id_29e533_idx'), models.Index(fields=['product', 'event'], name='collector_l_product_2afd77_idx'), models.Index(fields=['session_id'], name='collector_l_session_e56f71_idx'), models.Index(fields=['timestamp'], name='collector_l_timesta_4906b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('rating_type', models.CharField(choices=[('explicit', 'Explicit Rating'), ('implicit', 'Implicit Rating')], default='explicit', max_length=20)),
                ('confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.CharField(blank=True, help_text='Nguồn gốc rating: review, purchase, view, etc.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings',
                'indexes': [models.Index(fields=['user', 'product'], name='ratings_user_id_28c29b_idx'), models.Index(fields=['rating_type'], name='ratings_rating__ee5a7d_idx'), models.Index(fields=['created_at'], name='ratings_created_7f1288_idx')],
                'unique_together': {('user', 'product', 'rating_type')},
            },
        ),
    ]
