# Generated by Django 4.2 on 2025-12-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='source',
            field=models.CharField(blank=True, help_text='Nguồn gốc rating: review, calculated, manual, etc.', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='collectorlog',
            index=models.Index(fields=['event'], name='collector_l_event_820ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['score'], name='ratings_score_317b45_idx'),
        ),
    ]
