# Generated by Django 5.2.7 on 2025-12-24 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='Điểm tương đồng (0-1), càng cao càng giống')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm tính toán')),
                ('source', models.ForeignKey(help_text='Sản phẩm nguồn', on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='products.product')),
                ('target', models.ForeignKey(help_text='Sản phẩm tương tự', on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='products.product')),
            ],
            options={
                'db_table': 'product_similarities',
                'ordering': ['-similarity_score'],
                'indexes': [models.Index(fields=['source', '-similarity_score'], name='product_sim_source__7d7198_idx'), models.Index(fields=['target', '-similarity_score'], name='product_sim_target__91267c_idx'), models.Index(fields=['similarity_score'], name='product_sim_similar_b36573_idx'), models.Index(fields=['created_at'], name='product_sim_created_0e758c_idx')],
                'unique_together': {('source', 'target')},
            },
        ),
    ]
