# Generated by Django 5.2.7 on 2025-12-21 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_document_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
