# Generated by Django 5.2.7 on 2025-12-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_discount_code_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Delivered'), (3, 'Returned'), (4, 'Cancelled'), (5, 'Completed')], default=0),
        ),
    ]
