# Generated by Django 5.2.7 on 2025-12-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(default='TEMPORDER', editable=False, max_length=20, unique=True),
        ),
    ]
