# Generated by Django 5.2.7 on 2025-12-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_return',
            field=models.IntegerField(blank=True, choices=[(0, 'No return'), (1, 'Returned'), (2, 'Not processed')], default=2, null=True),
        ),
    ]
